# Generated by Django 5.0.3 on 2024-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_category_category_name_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
