# Generated by Django 5.0.2 on 2024-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_records_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='score',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
