# Generated by Django 5.0.2 on 2024-04-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_records_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
